// Code generated by go generate; DO NOT EDIT.
// This file was generated
//

package application

import (
	"github.com/dozer111/projectlinter-core/rules/dependency/bump"
)

var bumpLibraryConfigs = []bump.Library{
	{
		Name:    "doctrine/dbal",
		Version: "3.0.0",
		Description: []string{
			"Why not?",
			"dbal v2 is an oooooold legacy",
		},
		Examples: []bump.Example{
			{
				ProjectName: "auth-sv v2=>v3",
				Programmer:  "dozer111",
				Links: []string{
					"https://your_git.com/auth-sv/pull-requests/65/commits/afc2684feff4bfe919d17b03ab19d662aa6621b9",
				},
			},
			{
				ProjectName: "payment-sv v1=>v3",
				Programmer:  "onyxia",
				Links: []string{
					"https://your_git.com/payment-sv/pull-requests/65/commits/bfe919d17b03ab19d662aa6621b9afc2684feff4",
				},
			},
		},
	},
	{
		Name:    "rector/rector",
		Version: "1.0",
		ResponsiblePersons: []string{
			"dozer111",
		},
		Examples: []bump.Example{
			{
				ProjectName: "php-template",
				Programmer:  "dozer111",
				Links: []string{
					"https://your_git.com/php-application-template/pull-requests/88/diff",
				},
			},
			{
				ProjectName: "auth-sv",
				Programmer:  "dozer111",
				Links: []string{
					"https://your_git.com/auth-sv/pull-requests/1405/diff",
				},
			},
		},
	},
	{
		Name:    "symfony/flex",
		Version: "2.0",
		Description: []string{
			"No additional work",
			"Just up the version",
		},
		ResponsiblePersons: []string{
			"dozer111",
		},
	},
}
