// Code generated by go generate; DO NOT EDIT.
// This file was generated
//

package application

import (
	"github.com/dozer111/projectlinter-core/rules/dependency/bump"
)

var bumpLibraryConfigs = []bump.Library{}
