// Code generated by go generate; DO NOT EDIT.
// This file was generated
//

package application

import (
	"github.com/dozer111/projectlinter-core/rules/dependency/substitute"
)

var substituteLibraryConfigs = []substitute.Library{
	{
		Name:     "github.com/mailru/easyjson",
		ChangeTo: "github.com/francoispqt/gojay",
		Description: []string{
			"We use both libraries for now",
			"And it is more and more harder to maintain both of them in services",
			"So we decided to drop easyjson, and use only faster gojay instead",
			"The switch is not so easy.",
			"You need to generate new gojay code via https://github.com/francoispqt/gojay/tree/master/gojay",
			"There must be tests on the structures. If it is absent - add",
		},
		ResponsiblePersons: []string{
			"mondolorian",
			"eop",
		},
		Examples: []substitute.Example{
			{
				ProjectName: "auth-sv",
				Programmer:  "mondolorian",
				Links: []string{
					"https://your_git.com/auth-sv/pull-requests/91/overview",
				},
			},
			{
				ProjectName: "yggdrasil-integration-sv",
				Programmer:  "eop",
				Links: []string{
					"https://your_git.com/payment-sv/commits/69a1bb1f09cbe5796f95edf7066be46effcd5ffe",
				},
			},
		},
	},
	{
		Name:     "private-custom-test-library",
		ChangeTo: "github.com/testcontainers/testcontainers-go",
		Description: []string{
			"On the tech meeting 2024-05-21 we agreed to stop using our custom test library",
			"And instead start to work with github.com/testcontainers/testcontainers-go",
			"It do the same things, so no problem at all",
			"The switch is easy(see examples)",
			"",
			"Also, we create task for drop the old library: https://your_jira.com/task-1234",
		},
		ResponsiblePersons: []string{
			"dozer111",
			"catLovers",
			"dondo",
		},
		Examples: []substitute.Example{
			{
				ProjectName: "auth-sv",
				Programmer:  "dozer111",
				Links: []string{
					"https://unitedltd_git.com/projects/core/repos/auth-sv/pull-requests/91/overview",
				},
			},
			{
				ProjectName: "yggdrasil-integration-sv",
				Programmer:  "catLovers",
				Links: []string{
					"https://unitedltd_git.com/projects/core/repos/payment-sv/commits/69a1bb1f09cbe5796f95edf7066be46effcd5ffe",
				},
			},
		},
	},
}
