// Code generated by go generate; DO NOT EDIT.
// This file was generated
//

package application

import (
	"github.com/dozer111/projectlinter-core/rules/dependency/substitute"
)

var substituteLibraryConfigs = []substitute.Library{
	{
		Name:     "code-tool/doctrine-jaeger-symfony-bridge",
		ChangeTo: "code-tool/doctrine-dbal-jaeger",
		Examples: []substitute.Example{
			{
				ProjectName: "auth-sv",
				Programmer:  "dozer111",
				Links: []string{
					"https://your_git.com/auth-sv/commits/c836698e64149412fab971e2252396e9370394f7",
					"https://your_git.com/auth-sv/commits/0ce7f3c9ee28c28d7ec96df459e45b443f3c16b6",
				},
			},
		},
	},
}
